### ISSUE TITLE
Permanent fluttering / knocking at the output modulation with latest image 2024-09-09

### ISSUE THREAD

**Issue by dl1nux** [Guru-RF/SVXSpot#16] opened 2024-11-18 21:11 UTC
Hi

I've been using the image from beginning of the year and it worked fine. Because of the upcoming change from our net to new certificate based network connection I've tried out the new image from 2024-09-09 and was mostly disappointed.

The biggest problem is, that the output modulation of the RF Guru has a loud and permanent fluttering / knocking. I have big problems to understand the people. This was from beginning on. I had nearly standard configuration an only set up the connection to our reflector network. I've tried a lot of configuration, but had no luck.

So I switched back to the older image (I kept the old card an tested with a new card) and now the RF Guru works again fine, the Hardware is ok. So something changed badly in this image. 

There were other bad changed for me (just to note it)
- switching to TG selection by CTCSS (what the heck?). Very bad choice, you can't select other talkgroups then programmed and you have to change CTCSS in the radio always. Who really needs this ? Didn't I understand it? It's far too complicated to use. In fact svxlink didn't start up correctly when you accidently delete the ctcss mapping or modify it incorrectly. And you won't know why ... (found it out by trial and error).
- switching audio processing from hardware based (sa818) to software based (svxlink) - why? Hardware based is always better.
- switching SQL detection from hardware based (GPIO) to CTCSS only. Why?

Well this can all be changed, but only with a lot of configuration work and knowledge.
But the main problem is still the audio output problem. No QSOs possible in this way. Modulation on the other side at your qso partner is ok, they can hear you good. But I can't understand them really good.

I hope you have a solution for that.

73
Attila DL1NUX

**Comment by ure** [comment] 2024-11-18 23:55
Hi Attila DL1NUX,

Thank you for your detailed feedback and for bringing these issues to our attention.

**Audio Output Problem:**

The fluttering/knocking audio issue you’ve described could potentially be caused by RFI/EMI interference. To rule this out, we recommend testing the device with a power bank in another room or outside, away from potential sources of interference. If the issue persists, please open a support ticket (info@rf.guru) so we can inspect the device and arrange for a replacement if it’s found to be faulty.

**CTCSS Implementation:**

We’ve transitioned to software-based CTCSS processing because the hardware implementation had several limitations. We received reports of false-positive detections by the chip for certain CTCSS IDs, which caused reliability issues. Implementing CTCSS in software has resolved these problems. Additionally, the hardware squelch occasionally detected erratically, which is also addressed in the software solution.

It’s important to note that you can still configure a single CTCSS group with a default talkgroup (TG) and switch talkgroups via DTMF commands, just as before. If only one CTCSS group is programmed, the behaviour remains consistent with previous versions. Many users, myself included, use the system in this way. The introduction of CTCSS groups was added following specific requests from Italian and Swedish users who benefit greatly from this functionality.

**Audio Processing:**

The shift from hardware-based audio processing (via the SA818 chip) to software-based audio processing (via SVXLink) was a carefully considered decision. Extensive testing and comparisons revealed that the software solution provides clearer and higher-quality audio output. While hardware-based filtering can be effective, the software approach offers greater flexibility and better results in this implementation.

**SQL Detection:**

Switching SQL detection from hardware-based GPIO to software-based CTCSS was necessary to streamline the system and address reliability issues observed with the previous setup.

While we understand that these changes may require adjustments to your configuration and workflow, they were implemented to improve reliability and provide a better overall user experience. The main concern, however, is the audio output issue, which must be resolved first. Please follow the troubleshooting steps outlined above and let us know the outcome (info@rf.guru). If necessary, we are here to support you in resolving the problem.

Thank you for your understanding, and we appreciate your continued feedback to help us improve.

73, DE ON6URE

**Closed as completed** 2024-11-18 23:55 UTC

**Comment by dl1nux** [comment] 2024-11-19 18:58
Hi Jori
it is not RFI/EMI. The hardware works quite fine. I tested the Guru with ontop and external antenna outside on the roof. The problem is always there. As I mentioned, the older image works pretty fine without this issiue. This issue appears only when using the new image.  So there is any other problem occuring. I can try to make it again from scratch in the next days.

And the other mentioned points. I never had any problems ovserved with hardware based CTCSS, SQL or audioprocessing. It worked fine all the time.

Regards

**Comment by ure** [comment] 2024-11-19 20:07
Hi Attila,

Using an external antenna won’t fully determine if the issue is related to RFI/EMI. To properly test for that, you would need to move the device to another location and power it with a galvanically isolated supply, such as a power bank.

It’s highly unlikely that a software change would introduce audio issues. However, we’re happy to investigate further. We also offer a no-questions-asked replacement policy—just email us at info@rf.guru.

Best regards,
73 de ON6URE

**Comment by dl1nux** [comment] 2024-11-19 20:15
Hi
I repeat myself ... the guru works properly with the older image. Same place, same antenna, same power supply. Old image works. New image makes audio problems with sound like knocking.
I've tested also with a power bank. The knocking is still there. There is definitely no RFI/EMI Problem.
Using the old image helps. All totally clear.

**Comment by ure** [comment] 2024-11-19 20:37
Hi Attila,

Thank you for the clarification.

Since the issue cannot be reproduced on our side and you’ve ruled out RFI/EMI and power supply factors, the only way forward is to investigate the device directly. To save time and resolve this efficiently, we’d be happy to send you a replacement unit along with a return label for the current device. This will allow us to thoroughly examine the issue.

Please let us know your shipping details via info@rf.guru, and we’ll arrange everything promptly.

73 de ON6URE
